### ISSUE TITLE
cannot import name 'debug'

### ISSUE THREAD

**Issue by Diankuang-Wu** [PaulDanielML/MuJoCo_RL_UR5#1]
Hello, I run the command: python Grasping_Agent.py, in my conda virtual env(python3.6), facing an issue as below:

File "/home/wu/github_resource/MuJoCo_RL_UR5/gym_grasper/envs/GraspingEnv.py", line 19, in <module>
    from decorators import debug
**ImportError: cannot import name 'debug'**

my environment should be ok, ubuntu18.04, mujoco_py2.0, gym, and other ones required, like your requirements.txt

and the decorators module has been installed.

I search some messages by google, but useful ones are few.

so, how can I do to figure out this issue.

could you give me some suggestions, thank you~~

**Comment by PaulDanielML** [comment]
Hi,

the decorators import is my own local decorators file. As this is a work in progress, it will be imported in some of the files and these imports will also be pushed to the remote. 
I suggest you simply comment out the lines where it gets imported for now, as the decorators don't do anything other than debugging. I will exclude the decorators file from the .gitignore for the next push I do, so there won't be any errors raised anymore.

**Comment by Diankuang-Wu** [comment]
> Hi,
> 
> the decorators import is my own local decorators file. As this is a work in progress, it will be imported in some of the files and these imports will also be pushed to the remote.
> I suggest you simply comment out the lines where it gets imported for now, as the decorators don't do anything other than debugging. I will exclude the decorators file from the .gitignore for the next push I do, so there won't be any errors raised anymore.

Thank you, author. I comment out the related lines, it works. Now, I am very expected the codes after improving. whether there is a paper relating this repository by your writing, if so, please add the link, I want to study it, thank you again~

**Comment by PaulDanielML** [comment]
There might be a paper on this at some point, but that's not sure yet :) 
The main contribution of this repo is to provide a Gym-environment that implements a more realistic grasping process. 
It might not be the best environment if you are just getting started, as the observation - and actionspace are rather large.
I have gotten good results using deep Q-learning, with one ResNet for perception and one ResNet for predicting pixel wise success chances (see file Grasping_Agent.py)
The next iteration of the environment will introduce the grasping height as another action for the agent to choose. At this point the actionspace will likely get too large for value-based methods and instead might require the use of a policy-based algorithm.
