### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ChenyangRan** [PaulDanielML/MuJoCo_RL_UR5#3]
Hi, when I test your code, a segmentation fault happended.
Could you help me?
![Screenshot from 2020-10-23 22-13-32](https://user-images.githubusercontent.com/29306735/97014542-0d1c8400-157d-11eb-8a5d-71cca4b1ee3a.png)

**Comment by PaulDanielML** [comment]
Hi, what version of Python are you using? 
Also the command line argument you use is new, did you modify the code to support it?

**Comment by ChenyangRan** [comment]
> Hi, what version of Python are you using?
> Also the command line argument you use is new, did you modify the code to support it?
Hi, my python is 3,7 and the torch is 1.6.0.
I have tested the example.py and example_agent.py, which work well. I haven't modified the code.
Could you please tell me where I should modify?

**Comment by ChenyangRan** [comment]
Hi, I have sloved the problem. The segmentation is from the sunmmarywriter. And I just change the order and it can work.

**Comment by tjma005** [comment]
Hi, I met the same problem when running the example_agent.py, my python is 3.6. When I change the "render=True" to the "render=False", the problem gone. Is that the problem of the version of mujoco?
